name: screen_pixel
description: "A Flutter plugin to get screen resolution on macOS and Windows."
version: 0.0.2
homepage: https://github.com/blinkwhale/screen_pixel

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: ScreenPixelPlugin
      windows:
        pluginClass: ScreenPixelPluginCApi
